### ISSUE TITLE
GACODE environment on NERSC is broken after OS upgrade

### ISSUE THREAD

**Issue by odstrcilt** [gafusion/gacodeusers#10]
environment in file default GACODE isntalation on NESRC
 /global/cfs/cdirs/atom/atom-install-cori/gacode-source-mkl/platform/env/env.CORI_KNL_HT2_MKL
is not working. First issue is with intel libraries. 

```
# Intel 19 is broken
module swap intel/19.0.3.199 intel/18.0.3.222
```
but intel/18.0.3.222 does not exist anymore and only intel 19 is available. 
The other issue which I found is with cgyro_plot trying to print any LATEX symbols:

```
RuntimeError: latex was not able to process the following string:
b'$\\\\mathrm{Energy~flux} \\\\quad [60.0 < (c_s/a) t < 116.0]\\\\quad [\\\\mathrm{Total}]$'
```
I'm actually surprised that this was working before, because the right syntax is 
`r'$\mathrm{Energy~flux} \quad [60.0 < (c_s/a) t < 116.0]\quad [\mathrm{Total}]$'`
or 
`'$\\mathrm{Energy~flux} \\quad [60.0 < (c_s/a) t < 116.0]\\quad [\\mathrm{Total}]$'`

**Comment by bellie** [comment]
There was a maintenance and software upgrade of Cori yesterday.  We are recompiling the code now.

**Comment by jcandy** [comment]
I have rebuilt. Please be on the lookout for issues with `intel/19.1.2.254`  In the past we have downgraded from 19 to 18, but this is no longer an option.

To avoid the latex issues, use the `-notex` flag.
