### ISSUE TITLE
Units of qpar_beam in input.gacode

### ISSUE THREAD

**Issue by odstrcilt** [gafusion/gacodeusers#11]
What are units of qpar_beam and qpar_wall in input.gacode? In the file header is unit MW/m^3, but the values are of the order of 10^20. I have used profile_gen to create this file from a statefile.

**Comment by jcandy** [comment]
The units you quote, I believe, are taken from an old version of GACODE. Here are the units given by the current version:

```
call expro_writev(expro_qpar_beam,nexp,'qpar_beam','1/m^3/s') 
call expro_writev(expro_qpar_wall,nexp,'qpar_wall','1/m^3/s')
```

**Comment by odstrcilt** [comment]
Thank you.
