### ISSUE TITLE
DLNTDR_1-3_SCALE and DLNNDR_1-3_SCALE now listed as bogus parameters, causing failure on cori

### ISSUE THREAD

**Issue by KyleJCallahan** [gafusion/gacodeusers#13]
Submitting nonlinear CGYRO jobs from OMFIT (unstable) to cori stopped working on ~8/10/22. Investigation into the issue identified cgyro.input parameters DLNTDR_1-3_SCALE and DLNNDR_1-3_SCALE now listed as bogus, causing a failure in batch.out. If possible, could these scaling parameters be restored (very useful for scanning gradients)?

![CGYRO_CORI_job_details](https://user-images.githubusercontent.com/28585028/184945174-be85a8aa-c6bf-443d-a6bb-cd988e4cd6f7.png)

![batch out errors](https://user-images.githubusercontent.com/28585028/184945556-4f7e393c-d7ed-48a0-b981-793b4b6d8605.png)

**Comment by bellie** [comment]
For consistency with other species input parameters, we changed the name of these scaling parameters to put the species index at the end, i.e. DLNNDR_1_SCALE is now DLNNDR_SCALE_1 etc.
