### ISSUE TITLE
Issue with restarting the CGYRO job with DELTA_T_METHOD=1

### ISSUE THREAD

**Issue by odstrcilt** [gafusion/gacodeusers#14]
Sometimes it is not possible to restart the CGYRO job when the adaptive time step was used. CGYRO job ends without printing any error to batch.err or a warning to batch.out. The solution is simple, just reduce DELTA_T, but it would be nice if cgyro could print some integration error, like if the non-adaptive time step is used.

**Comment by bellie** [comment]
CGYRO error messages are printed to out.cgyro.info not batch.err or batch.out.  Did the job print any error messages to out.cgyro.info when it "failed".  Also the integration errors are still printed in out.cgyro.time even if adaptive time step is used.

**Comment by odstrcilt** [comment]
You are right, I forgot to check out.cgyro.info file. Thank you.
