### ISSUE TITLE
Low time step error Average function in gacodefuncs.py

### ISSUE THREAD

**Issue by maxtcurie** [gafusion/gacodeusers#15]
The source code 
/global/cfs/cdirs/atom/atom-install-cori/gacode-source-mkl/f2py/pygacode/gacodefuncs.py

The function cannot handle low counts of time steps for initial value solver. For example the test case reg08 will have error if one try to take the average of last 10% of time steps of total 4 time steps. Here is the error message: 

```
Traceback (most recent call last):
  File "/global/u1/m/maxcurie/CGYRO/toolbox/Intro.py", line 52, in <module>
    pfluxi = average(y[0,:],t,w,0.0)
  File "/global/cfs/cdirs/atom/atom-install-cori/gacode-source-mkl/f2py/pygacode/gacodefuncs.py", line 64, in average
    ave = ave/t_window
ZeroDivisionError: float division by zero
```

I have the following suggestion for average function. 

```
import numpy as np 

def average(f,t,wmin,wmax):

    n_time = len(t)

    tmin = (1.0-wmin)*t[-1]
    tmax = (1.0-wmax)*t[-1]

    tmin_index=np.argmin(abs(t-tmin))
    tmax_index=np.argmin(abs(t-tmin))

    # Manage case with 2 time points or less (eigenvalue)
    if tmax_index-tmin_index<=1:
        ave  = f[-1]
        
    else:
        t_window = 0.0
        ave      = 0.0
        for i in range(tmin_index,tmax_index+1):
            if t[i] >= tmin and t[i] <= tmax:
                ave = ave+0.5*(f[i]+f[i+1])*(t[i+1]-t[i])
                t_window = t_window+t[i+1]-t[i]
        ave = ave/t_window

    return ave
```

**Comment by bellie** [comment]
If you don't have enough time steps to average over the last x %, then increase the value of w.

**Comment by jcandy** [comment]
That is not a good fix because that is not the correct average. It just hides the error. Throwing an error (what happens now) is more suitable. An improvement would be to catch the error and inform the user more clearly about what happened. However, if you try to catch every possible error it leads to code bloat.
