### ISSUE TITLE
EQUILIBRIUM_MODEL=2: Name and Citation

### ISSUE THREAD

**Issue by cclauser** [gafusion/gacodeusers#7]
The CGYRO documentation says EQUILIBRIUM_MODEL=2 corresponds to the Miller's equilibrium parametrization.  However, I want to make sure that this is outdated and that now, EQUILIBRIUM_MODEL=2 corresponds to the Extended Miller's representation, given by Arbon PPCF 63 (2021). 
out.cgyro.info has printed: INFO: (CGYRO) Equilibrium: HAM

Thanks!
Cesar

**Comment by bellie** [comment]
Yes, the documentation is outdated.  EQUILIBRIUM_MODEL=2 is now the HAM (or MXH) method.

**Comment by cclauser** [comment]
Great, thank you!
