### ISSUE TITLE
Parallel submission of a large number of CGYRO jobs by TGYRO 

### ISSUE THREAD

**Issue by odstrcilt** [gafusion/gacodeusers#9]
NERSC on CORI intentionally limits the number of jobs users can run by accumulating priority with time only for the first two jobs for each QoS. Using TGYRO to manage multiple CGYRO jobs can therefore significantly improve the turnaround. 

Are there any limitations I should be aware of? Is it possible to run CGYRO on more than 1024 nodes to obtain the large job discount? 
I have copied my GACODE folder to the SCRATCH directory which should be faster than the home folder. 
Other options which could be tried is to use the Cori Burst Buffers a sbcast command to distribute the executable on the nodes.

**Comment by bellie** [comment]
Requesting more nodes may actually decrease throughput bc it will likely take a long time to fit-in.  If the goal is to increase throughput, then the optimal strategy is not TGYRO, but rather to request a shorter amount of time (<~ 2-4hrs) and to run using the flex queue.  In flex queue, it will try to get your job in for a set min time if it will fit (and will run to the max time if other jobs have lower priority after then min time).  To use flex queue: e.g, #SBATCH -q flex, #SBATCH --time-min=2:00:00, #SBATCH -t 3:59:00

If the goal is to get a discount, then the solution is also to use the flex queue, which has a 75% discount.  

I would not recommend using large nodes unless you really need it.  Larger number of nodes has higher chance of node failure.  Also, with TGYRO, if any one job fails, it will keep running until the clock runs out, so you will lose the time for any jobs that failed.

**Comment by odstrcilt** [comment]
I have tried flex queue last week and it was always running just for time-min, which cannot be longer than 2 hours and the waiting time was about 2 days.  Running two CGYRO instances, 20 nodes each,  in flex queue (only two jobs are accumulating priority with time, others are just staying there), allows me to use on average 40 knl node hours/day. It is actually counted as 40*0.2*0.25 = 2 node hours.  At this rate is not possible to use my allocation and finish all CGYRO runs in time. 

My current strategy is to merge several CGYRO runs together to use the 256 node limit of flex queue and wait ~4 days to start. Few jobs can fail, I'm expecting this.  But this is still too slow. Another option is a low priority queue or big job discount which not only reduces cost to halve but also increases priority. In any case, the emerging jobs by TGYRO is crucial to beat this two jobs per queue limit.

**Comment by bellie** [comment]
If the issue you are having is slow throughput, then the solution for this is to pay more by using the premium queue.  
Please do not waste resources to try to get your jobs to run faster by using larger number of nodes, unless the problem is actually scaling well for the individual node count and you really need to do that many physics simulations, as this is unfair to other users of the system.  [Also, the system goes through cycles of times that are busier than others.  If the time is available, the queue will allow more than 2 jobs to run at a time, if it does not impede another user's priority.]

**Comment by odstrcilt** [comment]
OK, I will be very cautious. I will modify a submission script to check the error output and if anything goes wrong, it will kill the whole job.  It would be useful to have an option in TGYRO to propagate errors from the managed codes.

**Comment by jcandy** [comment]
Collecting errors can only be done intrusively at the fortran level. The "correct" way to manage errors would be monitoring outside TGYRO at the system level and halting all jobs if an error is detected.
